AWSTemplateFormatVersion: "2010-09-09"

Description: "Route53 redirect from gramm.es to grammes.github.io"

Resources:

  # https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site
  RedirectA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z1045406BOC52TC75Q5N
      Name: gramm.es
      Type: A
      TTL: 3600 # seconds, 3600s = 1h
      ResourceRecords:
          - 185.199.108.153
          - 185.199.109.153
          - 185.199.110.153
          - 185.199.111.153
          
  RedirectWWW:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z1045406BOC52TC75Q5N
      Name: www.gramm.es
      Type: CNAME
      TTL: 3600 # seconds, 3600s = 1h
      ResourceRecords:
        - grammes.github.io
        
  RedirectIra:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z1045406BOC52TC75Q5N
      Name: ira.gramm.es
      Type: CNAME
      TTL: 3600 # seconds, 3600s = 1h
      ResourceRecords:
        - ira.gramm.es.s3.eu-central-1.amazonaws.com
        
  RedirectMail:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z1045406BOC52TC75Q5N
      Name: gramm.es
      Type: MX
      TTL: 3600 # seconds, 3600s = 1h
      ResourceRecords:
        - '10 mx1.improvmx.com.'
        - '20 mx2.improvmx.com.'

  ReduceSpam:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z1045406BOC52TC75Q5N
      Name: gramm.es
      Type: TXT
      TTL: 3600 # seconds, 3600s = 1h
      ResourceRecords:
        - '"v=spf1 -all"'
